# Generated by Django 4.0.6 on 2023-02-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stuname', models.CharField(max_length=20)),
                ('age', models.FloatField()),
            ],
        ),
    ]
