# Generated by Django 4.0.6 on 2023-02-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_location_profile_address_profile_phon_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phon_number',
            new_name='phone_number',
        ),
    ]
