# Generated by Django 4.0.6 on 2023-02-25 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_book_client_loan_remove_profile_user_delete_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
