# Generated by Django 4.0.6 on 2023-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookType',
            field=models.CharField(max_length=50),
        ),
    ]
