# Generated by Django 4.0.6 on 2023-03-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_book_booktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookType',
            field=models.IntegerField(),
        ),
    ]
