# Generated by Django 5.2.12 on 2026-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_book_booktype'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='returnDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
